### ISSUE TITLE
 FreeLing/APIs/java/FreelingSocketClient.java not working

### ISSUE THREAD

**Issue by jrmyr** [TALP-UPC/FreeLing#50] opened 2017-04-05 07:12 UTC
Hello,
the Java client provided in the project is not working. The initial connection to the Server succeeds (after quick-fixing the port parameter issue) but the "processSegment()" method does not provide a result.

**Comment by lluisp** [comment] 2017-04-05 08:03
It works for me...  Can you provide more details?
<code>
~$ analyze -f en.cfg --server --port 50005 &
SERVER: Analyzers loaded.

Launched server 5834 at port 50005

You can now analyze text with the following command:
  - From this computer: 
      analyzer_client 50005 <input.txt >output.txt
      analyzer_client localhost:50005 <input.txt >output.txt
  - From any other computer: 
      analyzer_client xorrai:50005 <input.txt >output.txt

Stop the server with: 
      analyze stop 5834

SERVER.DISPATCHER: Waiting for a free worker slot
SERVER.DISPATCHER: Waiting connections

~$ java FreelingSocketClient localhost
SERVER.DISPATCHER: Connection established. Forked worker 5867.
SERVER.DISPATCHER: Waiting for a free worker slot
SERVER.DISPATCHER: Waiting connections
the the DT 1
cat cat NN 1
eats eat VBZ 1
fresh fresh JJ 1
fish fish NN 0.845238
from from IN 1
the the DT 1
market market NN 0.985496
. . Fp 1

SERVER.WORKER: client ended. Closing connection.
</code>

**Comment by jrmyr** [comment] 2017-04-05 12:14
Hello,
thanks for the quick reply.
In our scenario freeling runs inside a self-constructed docker container and the port is exposed to the host. From the host I run the FreelingSocketClient.java compiled with Java 8 on Mac. The response I get is empty. I was able to create a Python client succeeding to get the wished result. But the FreelingSocketClient.java returns an empty result for the same input data and the same port.
If it works for you the problem might be in our config or start command:
`[path-to]/analyze --output naf -f [path-to]/ru.cfg --server --port 9520 &`
Even if I don't spot any strange things here.

**Comment by lluisp** [comment] 2017-04-05 14:47
I a python client works, then the problem is obviously in the java client.

did you make sure that the host is the docker container and not "localhost" ?

**Comment by jrmyr** [comment] 2017-04-06 06:18
I used localhost because the port from the docker container is exposed. As said, this works with the python client (using localhost and the exposed port). As I saw another little issue in the Java client (the port initialization: long is not allowed; must be int. But anyway it is overwritten by a hardcoded value in the Constructor, so no matter what's specified in the Constructor call), I thought it was maybe a work in progress class or something.

Running freeling natively is unfortunately not an option.

**Comment by lluisp** [comment] 2017-04-06 07:16
As far as I know, a docker container is a virtual machine, so it has a different IP than the host. If the server is running inside the container and the client is outside, you should use the container's IP (unless you have some kind of port forwarding, which I don't know if docker provides off-the-shlef...)

Regarding the long, yes, it should be int.  I changed that in the git master. You can get the latest version.
If it works in python in the same scenario, maybe the problem has to do with sockets in Java... I am afraid that this is beyond my expertise.

Apart from that, analyzer server and client are not even "work in progress".  They are just demos/examples of how it is possible to use FreeLing as a server. They are not intended to be used in a production environment. The communication does not follow any standard protocol, and has only very basic failsafe mechanisms.
If you use them in a production environment, do it at your own risk (Btw, if this is an commerical application, you'll need to acquire a dual license for FreeLing)

**Comment by jrmyr** [comment] 2017-04-06 07:51
Yes, docker supports port forwarding. This is what I use (and tried to explain above).
I was just playing around with it and stumbled upon the Java class issue and I thought it might be appreciated to be reported.

Thanks for your help.

If you're interested, this is the basic python (3.5) client succeeding to work:
```
import socket
text = 'Analyze me please'
soc = socket.socket()
soc.connect(("127.0.0.1", 50005))
soc.send((text + "\0").encode("utf8"))
result_bytes = soc.recv(4096)
soc.send("FLUSH_BUFFER\0".encode("utf8"))
result_bytes += soc.recv(4096)
print(result_bytes.decode("utf8")) 
```
Of course, it must be extended to work as a "real" client.

**Closed** 2017-04-18 13:11 UTC
